modLoader="javafml"
loaderVersion="[2,)"
license="MIT License https://github.com/McJtyMods/LostSouls/blob/1.18/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/LostSouls/issues"
displayURL="http://github.com/McJtyMods/LostSouls/"
authors="McJty"

[[mods]]
modId="lostsouls"
version="${file.jarVersion}"
displayName="LostSouls"
description='''
Make Lost Cities a more dangerous place
'''
[[dependencies.lostsouls]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lostsouls]]
    modId="lostcities"
    mandatory=true
    versionRange="[1.21-8.2.1,)"
    ordering="AFTER"
    side="BOTH"
